# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BEJdzH95vewbQW-XuWgDUoI23l76gLKX
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime
import os

def fetch_gold_price():
    url = "https://gold.tanaka.co.jp/commodity/souba/d-gold.php"
    headers = {'User-Agent': 'Mozilla/5.0'}

    # ページを取得
    response = requests.get(url, headers=headers)
    response.encoding = response.apparent_encoding
    soup = BeautifulSoup(response.text, 'html.parser')

    # すべてのテーブルを取得し、1番目のテーブル（テーブル1）を指定
    tables = soup.find_all('table')
    if len(tables) < 2:
        print("必要なテーブルが見つかりませんでした。")
        return

    table = tables[1]
    rows = table.find_all('tr')

    # 金価格がある行（行1）を取得
    latest_row = rows[1]
    cols = latest_row.find_all('td')

    # 価格データの抽出（cols[1] が税込価格）
    if len(cols) >= 2:
        date_str = datetime.now().strftime("%Y-%m-%d")
        # カンマと「円」を取り除いて数値のみにする
        price_str = cols[1].get_text().strip().replace(',', '').replace('円', '')

        data = {
            "Date": date_str,
            "Price": price_str
        }
        print(f"取得データ: {data}")

        # CSV保存処理
        filename = "gold_price.csv"
        df = pd.DataFrame([data])

        # ファイルがなければヘッダーを書き込み、あれば追記
        file_exists = os.path.isfile(filename)
        df.to_csv(filename, mode='a', index=False, header=not file_exists, encoding='utf-8-sig')
        print(f"\n完了! {filename} に保存しました！")
    else:
        print("データ行から価格を取得できませんでした。")

if __name__ == "__main__":
    fetch_gold_price()
